<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>microsoft</name>
   <tag></tag>
   <elementGuidId>386b99f9-763c-4322-8320-7130b1178e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.hasChildnew.hasChildnew_1 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='top-navi']/li[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8651313-874c-44a7-90b3-322ecc439b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/microsoft-training-certification-courses</value>
      <webElementGuid>4184d8c2-e4a2-4e1b-96b4-1fc5334283ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microsoft</value>
      <webElementGuid>7f6b3463-ff1d-4eab-83b1-61b6beb15019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navi&quot;)/li[@class=&quot;sub-menu-big sub_1&quot;]/div[@class=&quot;wrapper sub-menu-hide&quot;]/ul[@class=&quot;scroll-pane first-sub&quot;]/li[@class=&quot;hasChildnew hasChildnew_1&quot;]/a[1]</value>
      <webElementGuid>d94d1472-7510-46f1-940c-efc5c7cd1447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='top-navi']/li[2]/div/ul/li[2]/a</value>
      <webElementGuid>1a1063aa-f0c6-4ba4-ba46-696457f7d50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Microsoft')]</value>
      <webElementGuid>d216fe8a-b3f4-4480-a4db-ebec72458091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Courses'])[1]/following::a[1]</value>
      <webElementGuid>95eb728e-6b95-4217-9c3e-749a6ad2ce34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Catalogue'])[1]/following::a[2]</value>
      <webElementGuid>6ec46841-c374-46bb-a08c-7a37a82fce2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AZ-104T00-A: Microsoft Azure Administrator'])[1]/preceding::a[1]</value>
      <webElementGuid>a3292211-0ee4-4bd0-97b3-cc5ae87a3e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PL-300T00: Microsoft Power BI Data Analyst'])[1]/preceding::a[2]</value>
      <webElementGuid>eb08dcd9-7dca-4d2b-b97d-afeaad9a0908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/microsoft-training-certification-courses')]</value>
      <webElementGuid>1c4b4dcc-d9d7-4907-bb4d-ca6efecf094f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a</value>
      <webElementGuid>5b15c832-c9ce-4aa8-87e2-28da1d7f2b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/microsoft-training-certification-courses' and (text() = 'Microsoft' or . = 'Microsoft')]</value>
      <webElementGuid>dcfbfd37-d075-4f07-bd61-165fc9f2f7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
