<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qubits</name>
   <tag></tag>
   <elementGuidId>b989ce20-3b75-4589-913b-645409c12452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='top-navi']/li/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c87b8d18-57b4-454d-84a4-e1cd9859f861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/qubits-test</value>
      <webElementGuid>f260bf4c-71ae-4241-8564-83a29ef62bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qubits</value>
      <webElementGuid>fce3e38a-a6db-4046-8ead-2821a7b329cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navi&quot;)/li[@class=&quot;sub-menu-big&quot;]/div[@class=&quot;wrapper sub-menu-hide&quot;]/ul[@class=&quot;scroll-pane first-sub&quot;]/li[@class=&quot;hasChildnew&quot;]/a[1]</value>
      <webElementGuid>341216d3-4d68-4713-8776-e71b8a6cab38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='top-navi']/li/div/ul/li[2]/a</value>
      <webElementGuid>72c101d7-9834-446a-9b9d-7b93e0929f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Qubits')]</value>
      <webElementGuid>fd348e01-6778-4390-acd1-fd1ce312eca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[2]/following::a[1]</value>
      <webElementGuid>2398b609-ce22-4e5a-ad58-2cce280e98ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/following::a[2]</value>
      <webElementGuid>cd7d5ca8-4f68-4070-abbb-7fac67eb25f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Training'])[1]/preceding::a[1]</value>
      <webElementGuid>841da365-99fd-4123-bdf4-d5ff71869fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leadership'])[1]/preceding::a[2]</value>
      <webElementGuid>52035a92-81de-42a8-904e-27638dbb0c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/qubits-test')]</value>
      <webElementGuid>a0e96448-c1ce-4b5c-90a5-90c0df342765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>5c8d4fcb-a105-4fe9-861b-c54834f63d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/qubits-test' and (text() = 'Qubits' or . = 'Qubits')]</value>
      <webElementGuid>cd134ad3-5ad9-4aa5-837f-8394509be54b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
