<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchTextbox</name>
   <tag></tag>
   <elementGuidId>eb6e0c5d-837c-43ac-a87b-e48fd849b925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75a04d16-139a-4d76-87a7-ab6082e1904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1b690d6d-93d7-4226-a192-4e983a667b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inpt qubitsSearch</value>
      <webElementGuid>a01d62e4-6f7d-4d82-a93f-619248cf1d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tag</value>
      <webElementGuid>ce122643-f52c-4fbb-8796-8390c30abef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c08e2f45-43af-42fc-8bbd-97ef35e764e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tag</value>
      <webElementGuid>29d35d73-18a6-4c54-901d-9b7937a1cd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to learn?</value>
      <webElementGuid>bfbd6f15-6ef4-4fb1-abc1-699bc0a68a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>977acdb6-e1ed-4464-9ae3-7c6bd64f7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f66049a-7519-420e-84d9-2a82c6f793d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refresh&quot;)/div[@class=&quot;srchBox&quot;]/div[@class=&quot;inptBox&quot;]/input[@id=&quot;tag&quot;]</value>
      <webElementGuid>55912b84-c5bf-44b5-9a4a-8f18f5e0b2a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tag']</value>
      <webElementGuid>2f0437da-eeb4-472d-87dd-d10641bf3a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='refresh']/div/div/input</value>
      <webElementGuid>28c038ce-f65b-4c81-ada7-7c41f04762ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::input[1]</value>
      <webElementGuid>1966d55a-3745-44b4-ac77-a6eb382abcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::input[1]</value>
      <webElementGuid>3a1ed7e3-05ab-4958-b4e5-e16756bb0104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Search'])[1]/preceding::input[1]</value>
      <webElementGuid>0c41f99d-32c5-4b96-a244-b9f9f0eb81ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7fed43e-46f3-4212-836e-20dde3f6e1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tag' and @name = 'tag' and @placeholder = 'What do you want to learn?' and @type = 'text']</value>
      <webElementGuid>149759da-330b-4f72-91b3-db4008299728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
